/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { StudentClassEnrollment } from "./StudentClassEnrollment";
import { StudentClassEnrollmentCountArgs } from "./StudentClassEnrollmentCountArgs";
import { StudentClassEnrollmentFindManyArgs } from "./StudentClassEnrollmentFindManyArgs";
import { StudentClassEnrollmentFindUniqueArgs } from "./StudentClassEnrollmentFindUniqueArgs";
import { DeleteStudentClassEnrollmentArgs } from "./DeleteStudentClassEnrollmentArgs";
import { StudentClassEnrollmentService } from "../studentClassEnrollment.service";
@graphql.Resolver(() => StudentClassEnrollment)
export class StudentClassEnrollmentResolverBase {
  constructor(protected readonly service: StudentClassEnrollmentService) {}

  async _studentClassEnrollmentsMeta(
    @graphql.Args() args: StudentClassEnrollmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [StudentClassEnrollment])
  async studentClassEnrollments(
    @graphql.Args() args: StudentClassEnrollmentFindManyArgs
  ): Promise<StudentClassEnrollment[]> {
    return this.service.studentClassEnrollments(args);
  }

  @graphql.Query(() => StudentClassEnrollment, { nullable: true })
  async studentClassEnrollment(
    @graphql.Args() args: StudentClassEnrollmentFindUniqueArgs
  ): Promise<StudentClassEnrollment | null> {
    const result = await this.service.studentClassEnrollment(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => StudentClassEnrollment)
  async deleteStudentClassEnrollment(
    @graphql.Args() args: DeleteStudentClassEnrollmentArgs
  ): Promise<StudentClassEnrollment | null> {
    try {
      return await this.service.deleteStudentClassEnrollment(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
